apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          preference:
          - matchExpressions:
            - key: disk
              operator: In
              values:
              - ssd
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/nginx:1.29
        name: nginx
        imagePullPolicy: IfNotPresent
