FROM ubuntu:latest

LABEL AUTHOR="Jeganathan Swaminathan"
LABEL EMAIL="jegan@tektutor.org"

RUN apt update && apt install -y git net-tools iputils-ping 
RUN apt update && apt install -y vim default-jdk maven
