apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc-jegan  #Replace 'jegan' with your name

      containers:
      - name: wordpress
        image: image-registry.openshift-image-registry.svc:5000/openshift/wordpress:6.8.2
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/mariadb/data

        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-credentials
              key: username

        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-credentials
              key: password 

        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-configuration
              key: db_name

        - name: WORDPRESS_DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: wordpress-configuration
              key: db_host

        - name: WORDPRESS_DATABASE_PORT
          valueFrom: 
            configMapKeyRef:
              name: wordpress-configuration
              key: db_port
