apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv{{.Values.your_name}}
  labels:
    name: {{.Values.your_name}} 
spec:
  capacity:
    storage: {{.Values.wordpress_pv_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # All the pods from any node in the openshift cluster can read & write this external storage
  persistentVolumeReclaimPolicy: Retain

  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.nfs_wordpress_path}} 
