apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc{{.Values.your_name}}
spec:
  selector:
    matchLabels:
      name: {{.Values.your_name}} 
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.wordpress_pv_size}}
